# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS-10.13'

variables:
  scheme: 'Provenance-Release'
  sdk: 'iphoneos'
  configuration: 'Release'
  target: 'Provenance'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    target:  '$(target)'
    xcWorkspacePath: 'Provenance.xcworkspace'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    xcodeVersion: '10' # Options: 8, 9, default, specifyPath
    destinationPlatformOption: 'iOS'
    destinationTypeOption: 'devices' # Optional. Options: simulators, devices
    packageApp: true
    #signingOption: 'nosign' # Optional. Options: nosign, default, manual, auto
    #signingIdentity: # Optional
    #provisioningProfileUuid: # Optional
    #provisioningProfileName: # Optional
    #teamId: # Optional
    # Additional options https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=vsts

# Install Apple Certificate
# Install an Apple certificate required to build on a macOS agent
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-certificate?view=vsts
# - task: InstallAppleCertificate@2
#   inputs:
    # certSecureFile: 
    #certPwd: # Optional
    #keychain: 'temp' # Options: default, temp, custom
    #keychainPassword: # Required when keychain == Custom || Keychain == Default
    #customKeychainPath: # Required when keychain == Custom
    #deleteCert: # Optional
    #deleteCustomKeychain: # Optional
    #signingIdentity: # Optional

# Install Apple Provisioning Profile
# Install an Apple provisioning profile required to build on a macOS agent
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=vsts
# - task: InstallAppleProvisioningProfile@1
  # inputs:
    #provisioningProfileLocation: 'secureFiles' # Options: secureFiles, sourceRepository
    #provProfileSecureFile: # Required when provisioningProfileLocation == SecureFiles
    #provProfileSourceRepository: # Required when provisioningProfileLocation == SourceRepository
    #removeProfile: # Optional

# App Center Distribute
# Distribute app builds to testers and users via App Center
# - task: AppCenterDistribute@1
#   inputs:
#     serverEndpoint: 
#     appSlug: 
#     appFile: 
    #symbolsOption: 'Apple' # Optional. Options: apple
    #symbolsPath: # Optional
    #symbolsPdbFiles: '**/*.pdb' # Optional
    #symbolsDsymFiles: # Optional
    #symbolsMappingTxtFile: # Optional
    #symbolsIncludeParentDirectory: # Optional
    #releaseNotesOption: 'input' # Options: input, file
    #releaseNotesInput: # Required when releaseNotesOption == Input
    #releaseNotesFile: # Required when releaseNotesOption == File
    #distributionGroupId: # Optional